'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Projects', [
      {
        name: 'Portfolio Website',
        description: 'Personal portfolio showcasing projects and skills.',
        techStackId: 1, 
        studentId: 1,
        developmentArea: 'Frontend',
        gitHub: 'https://github.com/student1/portfolio',
        website: 'https://student1-portfolio.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'E-commerce Backend',
        description: 'Backend API for an e-commerce platform.',
        techStackId: 2, 
        studentId: 2,
        developmentArea: 'Backend',
        gitHub: 'https://github.com/student2/ecommerce-backend',
        website: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Blog Platform',
        description: 'A fullstack blog publishing platform.',
        techStackId: 1,
        studentId: 3,
        developmentArea: 'Fullstack',
        gitHub: 'https://github.com/student3/blog-platform',
        website: 'https://blog.student3.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Chat Application',
        description: 'Real-time chat application using websockets.',
        techStackId: 3,
        studentId: 4,
        developmentArea: 'Fullstack',
        gitHub: 'https://github.com/student4/chat-app',
        website: 'https://chat.student4.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Task Manager',
        description: 'Task management web app with reminders and notes.',
        techStackId: 1,
        studentId: 5,
        developmentArea: 'Frontend',
        gitHub: 'https://github.com/student5/task-manager',
        website: 'https://tasks.student5.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Inventory System',
        description: 'Inventory tracking system for small businesses.',
        techStackId: 4, 
        studentId: 6,
        developmentArea: 'Backend',
        gitHub: 'https://github.com/student6/inventory-system',
        website: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Fitness Tracker',
        description: 'Mobile app for tracking workouts and nutrition.',
        techStackId: 5, 
        studentId: 7,
        developmentArea: 'Frontend',
        gitHub: 'https://github.com/student7/fitness-tracker',
        website: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Online Learning Platform',
        description: 'Platform to host courses and video tutorials.',
        techStackId: 1,
        studentId: 8,
        developmentArea: 'Fullstack',
        gitHub: 'https://github.com/student8/learning-platform',
        website: 'https://learn.student8.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Food Delivery App',
        description: 'Backend services for food delivery with real-time tracking.',
        techStackId: 2,
        studentId: 9,
        developmentArea: 'Backend',
        gitHub: 'https://github.com/student9/food-delivery-backend',
        website: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Weather Dashboard',
        description: 'Frontend dashboard for weather forecasting data.',
        techStackId: 1,
        studentId: 10,
        developmentArea: 'Frontend',
        gitHub: 'https://github.com/student10/weather-dashboard',
        website: 'https://weather.student10.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Expense Tracker',
        description: 'App to track personal expenses and budgets.',
        techStackId: 3,
        studentId: 11,
        developmentArea: 'Fullstack',
        gitHub: 'https://github.com/student11/expense-tracker',
        website: 'https://expenses.student11.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Event Management System',
        description: 'System to organize and manage events.',
        techStackId: 4,
        studentId: 12,
        developmentArea: 'Backend',
        gitHub: 'https://github.com/student12/event-management',
        website: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Social Media App',
        description: 'Mobile app for sharing photos and posts.',
        techStackId: 5,
        studentId: 13,
        developmentArea: 'Fullstack',
        gitHub: 'https://github.com/student13/social-media-app',
        website: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Travel Blog',
        description: 'Personal travel blog site.',
        techStackId: 1,
        studentId: 14,
        developmentArea: 'Frontend',
        gitHub: 'https://github.com/student14/travel-blog',
        website: 'https://travel.student14.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Booking System',
        description: 'System to manage hotel and flight bookings.',
        techStackId: 2,
        studentId: 15,
        developmentArea: 'Backend',
        gitHub: 'https://github.com/student15/booking-system',
        website: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Recipe App',
        description: 'App to browse and save cooking recipes.',
        techStackId: 3,
        studentId: 16,
        developmentArea: 'Fullstack',
        gitHub: 'https://github.com/student16/recipe-app',
        website: 'https://recipes.student16.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Portfolio Builder',
        description: 'Tool to create and share developer portfolios.',
        techStackId: 1,
        studentId: 17,
        developmentArea: 'Frontend',
        gitHub: 'https://github.com/student17/portfolio-builder',
        website: 'https://portfolio.student17.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Job Portal',
        description: 'Platform to apply for and manage job listings.',
        techStackId: 2,
        studentId: 18,
        developmentArea: 'Fullstack',
        gitHub: 'https://github.com/student18/job-portal',
        website: 'https://jobs.student18.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Chatbot',
        description: 'AI-powered chatbot for customer support.',
        techStackId: 4,
        studentId: 19,
        developmentArea: 'Backend',
        gitHub: 'https://github.com/student19/chatbot',
        website: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'News Aggregator',
        description: 'App to aggregate news from multiple sources.',
        techStackId: 1,
        studentId: 20,
        developmentArea: 'Fullstack',
        gitHub: 'https://github.com/student20/news-aggregator',
        website: 'https://news.student20.com',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Projects', null, {});
  }
};
