'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Students', [
    {
      firstName: 'Arjun',
      lastName: 'Kumar',
      userName: 'arjun.k',
      email: 'arjun.kumar@example.com',
      phoneNumber: '9876543210',
      description: 'Passionate about fullstack development and AI.',
      qualificationId: 1, 
      departmentId: 1, 
      collegeId: 1, 
      roleId: 2, 
      currentYear: 'FinalYear',
      currentStatus: 'Employed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Sneha',
      lastName: 'Iyer',
      userName: 'sneha.iyer',
      email: 'sneha.iyer@example.com',
      phoneNumber: '9876512340',
      description: 'Interested in Data Science and Machine Learning.',
      qualificationId: 2, 
      departmentId: 8, 
      collegeId: 2, 
      roleId: 2,
      currentYear: 'Year3',
      currentStatus: 'Intership',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Ravi',
      lastName: 'Sharma',
      userName: 'ravi.sharma',
      email: 'ravi.sharma@example.com',
      phoneNumber: '9988776655',
      description: 'Aspiring cybersecurity analyst.',
      qualificationId: 5, 
      departmentId: 10, 
      collegeId: 3, 
      roleId: 2,
      currentYear: 'Year2',
      currentStatus: 'NotEmployed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Pooja',
      lastName: 'Menon',
      userName: 'pooja.m',
      email: 'pooja.menon@example.com',
      phoneNumber: '9876001122',
      description: 'Specializes in frontend development with React.',
      qualificationId: 4, 
      departmentId: 7, 
      collegeId: 4, 
      roleId: 2,
      currentYear: 'Year1',
      currentStatus: 'Intership',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Aditya',
      lastName: 'Gupta',
      userName: 'aditya.g',
      email: 'aditya.gupta@example.com',
      phoneNumber: '9876123456',
      description: 'Focused on backend APIs and database management.',
      qualificationId: 1,
      departmentId: 2,
      collegeId: 5, 
      roleId: 2,
      currentYear: 'Year3',
      currentStatus: 'Employed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Deepika',
      lastName: 'Rao',
      userName: 'deepika.rao',
      email: 'deepika.rao@example.com',
      phoneNumber: '9988123456',
      description: 'Machine Learning enthusiast and researcher.',
      qualificationId: 2, 
      departmentId: 9, 
      collegeId: 6, 
      roleId: 2,
      currentYear: 'FinalYear',
      currentStatus: 'NotEmployed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Karthik',
      lastName: 'Iyer',
      userName: 'karthik.iyer',
      email: 'karthik.iyer@example.com',
      phoneNumber: '9876543211',
      description: 'Fullstack developer with passion for React and Node.',
      qualificationId: 1, 
      departmentId: 1, 
      collegeId: 7, 
      roleId: 2,
      currentYear: 'Year2',
      currentStatus: 'Employed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Anjali',
      lastName: 'Shah',
      userName: 'anjali.shah',
      email: 'anjali.shah@example.com',
      phoneNumber: '9876543222',
      description: 'Cybersecurity analyst and ethical hacker.',
      qualificationId: 5, 
      departmentId: 10, 
      collegeId: 8, 
      roleId: 2,
      currentYear: 'PassedOut',
      currentStatus: 'Employed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Vikram',
      lastName: 'Singh',
      userName: 'vikram.singh',
      email: 'vikram.singh@example.com',
      phoneNumber: '9876543233',
      description: 'Data scientist working on NLP projects.',
      qualificationId: 3, 
      departmentId: 8, 
      collegeId: 9, 
      roleId: 2,
      currentYear: 'Year3',
      currentStatus: 'Intership',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Sonal',
      lastName: 'Patel',
      userName: 'sonal.patel',
      email: 'sonal.patel@example.com',
      phoneNumber: '9876543244',
      description: 'Frontend developer with expertise in Vue.js.',
      qualificationId: 4, 
      departmentId: 7, 
      collegeId: 10, 
      roleId: 2,
      currentYear: 'FinalYear',
      currentStatus: 'Employed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Rohit',
      lastName: 'Desai',
      userName: 'rohit.desai',
      email: 'rohit.desai@example.com',
      phoneNumber: '9876543255',
      description: 'Backend developer specializing in Node.js and Express.',
      qualificationId: 1, 
      departmentId: 2, 
      collegeId: 1, 
      roleId: 2,
      currentYear: 'Year1',
      currentStatus: 'NotEmployed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Meera',
      lastName: 'Iyer',
      userName: 'meera.iyer',
      email: 'meera.iyer@example.com',
      phoneNumber: '9876543266',
      description: 'Interested in AI and deep learning.',
      qualificationId: 2, 
      departmentId: 9, 
      collegeId: 2, 
      roleId: 2,
      currentYear: 'FinalYear',
      currentStatus: 'Employed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Harsh',
      lastName: 'Kumar',
      userName: 'harsh.kumar',
      email: 'harsh.kumar@example.com',
      phoneNumber: '9876543277',
      description: 'Mobile app developer with Flutter expertise.',
      qualificationId: 4, 
      departmentId: 7, 
      collegeId: 3, 
      roleId: 2,
      currentYear: 'Year3',
      currentStatus: 'Intership',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Nisha',
      lastName: 'Singh',
      userName: 'nisha.singh',
      email: 'nisha.singh@example.com',
      phoneNumber: '9876543288',
      description: 'Fullstack developer focusing on React and MongoDB.',
      qualificationId: 1, 
      departmentId: 1, 
      collegeId: 4, 
      roleId: 2,
      currentYear: 'Year2',
      currentStatus: 'Employed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Amit',
      lastName: 'Verma',
      userName: 'amit.verma',
      email: 'amit.verma@example.com',
      phoneNumber: '9876543299',
      description: 'Cloud computing and DevOps enthusiast.',
      qualificationId: 3, 
      departmentId: 5, 
      collegeId: 5, 
      roleId: 2,
      currentYear: 'Year1',
      currentStatus: 'NotEmployed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Riya',
      lastName: 'Patel',
      userName: 'riya.patel',
      email: 'riya.patel@example.com',
      phoneNumber: '9876543300',
      description: 'Specializes in frontend and UI/UX design.',
      qualificationId: 4, 
      departmentId: 7, 
      collegeId: 6, 
      roleId: 2,
      currentYear: 'FinalYear',
      currentStatus: 'Employed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Suresh',
      lastName: 'Kumar',
      userName: 'suresh.kumar',
      email: 'suresh.kumar@example.com',
      phoneNumber: '9876543311',
      description: 'Data analyst and visualization expert.',
      qualificationId: 3, 
      departmentId: 8, 
      collegeId: 7, 
      roleId: 2,
      currentYear: 'PassedOut',
      currentStatus: 'Employed',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      firstName: 'Kavya',
      lastName: 'Joshi',
      userName: 'kavya.joshi',
      email: 'kavya.joshi@example.com',
      phoneNumber: '9876543322',
      description: 'AI researcher focusing on computer vision.',
      qualificationId: 5, 
      departmentId: 9, 
      collegeId: 8, 
      roleId: 2,
      currentYear: 'FinalYear',
      currentStatus: 'Intership',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
  firstName: 'Aarav',
  lastName: 'Sharma',
  userName: 'aaravsharma',
  email: 'aarav.sharma@example.com',
  phoneNumber: '9876543210',
  description: 'Passionate about AI and Machine Learning.',
  qualificationId: 2,  
  departmentId: 9,     
  collegeId: 6,        
  roleId: 2,           
  currentYear: 'FinalYear',
  currentStatus: 'NotEmployed',
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  firstName: 'Meera',
  lastName: 'Patel',
  userName: 'meerapatel',
  email: 'meera.patel@example.com',
  phoneNumber: '9123456780',
  description: 'Interested in Frontend Development and UI/UX.',
  qualificationId: 4,  
  departmentId: 1,     
  collegeId: 3,        
  roleId: 2,           
  currentYear: 'Year3',
  currentStatus: 'Intership',
  createdAt: new Date(),
  updatedAt: new Date()
}
  ], {});
  },

  async down (queryInterface, Sequelize) {
  await queryInterface.bulkDelete('Students', null, {});
  }
};
